SED-1636-New query builder logic
exense/step-framework pull request #19
Opened 2023-04-05 22:13 UTC by lucianbaciu

I will summarize below the changes via a few example, so you can get the actual behavior:

Let's assume we have a pipeline with resolution = 500

There are 2 big options when asking for an aggregation: **Window** (custom resolution in response) and **Split** (number of buckets)

Window examples:
range [0, 2000) =>this will create one bucket / source resolution. result intervals = 0, 500, 1000, 1500
range [0, 2000) + window(600) => window will be rounded to the closest source multiplier = 500. same result as above
range [0, 3000) + window(1200) => result = [0, 1000, 2000], and result resolution = 1000
range [400, 2000) => the range will alyways start from the lower source interval multiplier, so [0, 2000) in our case

Split examples:
range [0, 4000) + split(2) => result = [0, 2000)
range [0, 4000) + split(3) => range is transformed to [0, 4500], with resolution 1500, the result will be [0, 1500, 3000)
range [0, 4000) + split(7) => range is transformed to [0, 7000) because the resolution is too small, result being [0, 1000, 2000, 3000, 4000, 5000, 6000) - this is very unlikely to happen
range [0, 1000) + range(5) => this is the only situation when the buckets count is not respected, because the resolution don't allow us. [0, 500) is returned

2023-04-06 13:47 UTC, david-stephan commented
@lucianbaciu the change looks mostly good and functional. I think the 3 changes requested would help the readability of the code.
Regarding:
range [0, 4000) + split(7) => range is transformed to [0, 7000)  because the resolution is too small, result being [0, 1000, 2000, 3000, 4000, 5000, 6000) - this is very unlikely to happen
It would be nicer in this case to resolve to a resolution of 500 and 8 buckets.  Between the range and number of buckets the range has an higher priority from my point of view.

2023-04-06 17:48 UTC, lucianbaciu commented
@david-stephan I did it this way just to be a little more consistent. I think either way, it will have no bad effect overall. Let me know if you want me to change to work as described by you. Thanks!

2023-04-06 18:36 UTC, david-stephan commented
> @david-stephan I did it this way just to be a little more consistent. I think either way, it will have no bad effect overall. Let me know if you want me to change to work as described by you. Thanks!

Yes, please I think as a user I prefer to get a range closer to what I requested rather than the number of buckets.

2023-04-10 09:13 UTC, lucianbaciu commented
@david-stephan - The range stays now at close as possible to the requested values, instead of buckets count which took priority

2023-04-11 11:35 UTC, david-stephan requested changes
the last change for calculating the result resolution looks good. There are still 3 old comments and 2 new ones to be considered before approving the PR

2023-04-11 11:35 UTC, david-stephan commented on step-framework-parent/step-framework-timeseries/src/main/java/step/core/timeseries/aggregation/TimeSeriesAggregationQueryBuilder.java
> +                        resultTo = (long) Math.ceil((double)to / sourceResolution) * sourceResolution;
duplicate line 81

2023-04-11 11:35 UTC, david-stephan commented on step-framework-parent/step-framework-timeseries/src/main/java/step/core/timeseries/aggregation/TimeSeriesAggregationQueryBuilder.java
> +//                        resultTo = resultFrom + (resultResolution * bucketsCount);
remove comments

2023-04-12 06:30 UTC, david-stephan approved these changes

2023-04-12 06:31 UTC, merged