SED-2367-Added findByIds accesor method
exense/step-framework pull request #38
Opened 2023-11-02 14:10 UTC by lucianbaciu

2023-11-03 11:42 UTC, david-stephan requested changes
See comment

2023-11-03 11:42 UTC, david-stephan commented on step-framework-parent/step-framework-collections/src/main/java/step/core/accessors/Accessor.java
> +
Formatting indentation issue
Use directly a List, no need of collection and use "import" rather than having the package name here

2023-11-03 11:42 UTC, david-stephan commented on step-framework-parent/step-framework-collections/src/main/java/step/core/accessors/CachedAccessor.java
> +    @Override
Formatting indentation issue
Use directly a List, no need of collection and use "import" rather than having the package name here

2023-11-06 07:46 UTC, david-stephan requested changes

2023-11-06 07:46 UTC, david-stephan commented on step-framework-parent/step-framework-collections/src/main/java/step/core/accessors/AbstractAccessor.java
> +
indentation

2023-11-06 07:46 UTC, david-stephan commented on step-framework-parent/step-framework-collections/src/test/java/step/core/accessors/AbstractAccessorTest.java
> +
indentation

2023-11-06 16:46 UTC, lucianbaciu commented on step-framework-parent/step-framework-collections/src/test/java/step/core/accessors/AbstractAccessorTest.java
> +}
this empty line at the end is added automatically by someone (most likely my intellij), but all the files have it.

2023-11-06 16:46 UTC, lucianbaciu commented
@david-stephan you can recheck

2023-11-08 13:13 UTC, david-stephan approved these changes

2023-11-13 10:06 UTC, merged